name: Generate Datas
on:
  schedule: # executa a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Gera a animação da cobrinha
      - name: Generate snake animation
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: CeliaRaizer
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#3c7dd9&color_dots=#0a1929,#0d47a1,#1565c0,#1976d2,#42a5f5
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Publica o resultado na branch "output"
      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
          force_orphan: true
